name: 'Setup'
description: 'Setup Node.js environment with pnpm'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9.1.1

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
