name: 'Setup'
description: 'Setup Node.js environment with pnpm'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      shell: bash

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash
